import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../../models/poll_model.dart';
import '../../providers/polls_provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/user_provider.dart';
import '../../widgets/forms/styled_text_field.dart';
import '../../widgets/forms/tag_selector.dart';
import '../../widgets/buttons/primary_button.dart';
import '../../widgets/common/loading_indicator.dart';
import '../../config/constants.dart';

/// Screen for creating a new poll.
class AddPollScreen extends StatefulWidget {
  const AddPollScreen({super.key});

  @override
  State<AddPollScreen> createState() => _AddPollScreenState();
}

class _AddPollScreenState extends State<AddPollScreen> {
  final _formKey = GlobalKey<FormState>();
  final _questionController = TextEditingController();
  final List<TextEditingController> _answerControllers = [
    TextEditingController(),
    TextEditingController(),
  ];

  bool _isPersonal = true; // true = Personal Growth, false = Social & Political
  List<String> _selectedTags = [];
  bool _isLoading = false;

  @override
  void dispose() {
    _questionController.dispose();
    for (final controller in _answerControllers) {
      controller.dispose();
    }
    super.dispose();
  }

  void _addAnswerOption() {
    if (_answerControllers.length < AppConstants.maxPollAnswers) {
      setState(() {
        _answerControllers.add(TextEditingController());
      });
    }
  }

  void _removeAnswerOption(int index) {
    if (_answerControllers.length > 2) {
      setState(() {
        _answerControllers[index].dispose();
        _answerControllers.removeAt(index);
      });
    }
  }

  void _onCategoryChanged(bool isPersonal) {
    setState(() {
      _isPersonal = isPersonal;
      // Clear tags when category changes since tags are category-specific
      _selectedTags = [];
    });
  }

  void _onTagsChanged(List<String> tags) {
    setState(() {
      _selectedTags = tags;
    });
  }

  Future<void> _createPoll() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Validate that at least 2 answers are non-empty
    final nonEmptyAnswers = _answerControllers
        .map((c) => c.text.trim())
        .where((text) => text.isNotEmpty)
        .toList();

    if (nonEmptyAnswers.length < 2) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please provide at least 2 answer options'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final authProvider = context.read<AuthProvider>();
      final userProvider = context.read<UserProvider>();
      final pollsProvider = context.read<PollsProvider>();

      final userId = authProvider.userId;
      final user = userProvider.currentUser;

      if (userId == null || user == null) {
        throw Exception('You must be logged in to create a poll');
      }

      final poll = PollModel(
        id: '', // Will be generated by Firestore
        creatorUid: userId,
        creatorName: user.displayName,
        creatorPhotoUrl: user.photoUrl,
        question: _questionController.text.trim(),
        answers: nonEmptyAnswers,
        isPersonal: _isPersonal,
        tags: _selectedTags,
        createdAt: DateTime.now(),
        votedUserIds: [],
        voteCounts: List.filled(nonEmptyAnswers.length, 0),
      );

      final pollId = await pollsProvider.createPoll(poll);

      if (pollId != null && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Poll created successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        context.pop();
      } else if (mounted) {
        throw Exception(pollsProvider.error ?? 'Failed to create poll');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Poll'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.pop(),
        ),
      ),
      body: _isLoading
          ? const LoadingIndicator(message: 'Creating poll...')
          : Form(
              key: _formKey,
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  // Question Input
                  Text(
                    'Question',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  StyledTextField(
                    controller: _questionController,
                    hintText: 'Ask a question...',
                    maxLines: 3,
                    textCapitalization: TextCapitalization.sentences,
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter a question';
                      }
                      if (value.trim().length < 10) {
                        return 'Question must be at least 10 characters';
                      }
                      return null;
                    },
                  ),

                  const SizedBox(height: 24),

                  // Answer Options
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Answer Options',
                        style: theme.textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      if (_answerControllers.length < AppConstants.maxPollAnswers)
                        TextButton.icon(
                          onPressed: _addAnswerOption,
                          icon: const Icon(Icons.add, size: 18),
                          label: const Text('Add Option'),
                        ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  ...List.generate(_answerControllers.length, (index) {
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: Row(
                        children: [
                          Expanded(
                            child: StyledTextField(
                              controller: _answerControllers[index],
                              hintText: 'Option ${index + 1}',
                              textCapitalization: TextCapitalization.sentences,
                              validator: (value) {
                                // At least first 2 options are required
                                if (index < 2 &&
                                    (value == null || value.trim().isEmpty)) {
                                  return 'This option is required';
                                }
                                return null;
                              },
                            ),
                          ),
                          if (_answerControllers.length > 2)
                            IconButton(
                              onPressed: () => _removeAnswerOption(index),
                              icon: Icon(
                                Icons.remove_circle_outline,
                                color: theme.colorScheme.error,
                              ),
                              tooltip: 'Remove option',
                            ),
                        ],
                      ),
                    );
                  }),

                  const SizedBox(height: 24),

                  // Category Selection
                  Text(
                    'Category',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Expanded(
                        child: _CategoryOption(
                          title: 'Personal Growth',
                          isSelected: _isPersonal,
                          onTap: () => _onCategoryChanged(true),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _CategoryOption(
                          title: 'Social & Political',
                          isSelected: !_isPersonal,
                          onTap: () => _onCategoryChanged(false),
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: 24),

                  // Tag Selection
                  Text(
                    'Tags (Optional)',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Select up to ${AppConstants.maxTagsPerItem} tags to help others find your poll',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurface.withOpacity(0.6),
                    ),
                  ),
                  const SizedBox(height: 12),
                  _isPersonal
                      ? TagSelector.personalGrowth(
                          selectedTags: _selectedTags,
                          onChanged: _onTagsChanged,
                          maxSelections: AppConstants.maxTagsPerItem,
                        )
                      : TagSelector.socialPolitical(
                          selectedTags: _selectedTags,
                          onChanged: _onTagsChanged,
                          maxSelections: AppConstants.maxTagsPerItem,
                        ),

                  const SizedBox(height: 32),

                  // Create Button
                  PrimaryButton(
                    text: 'Create Poll',
                    onPressed: _createPoll,
                    icon: Icons.poll_outlined,
                  ),

                  const SizedBox(height: 24),
                ],
              ),
            ),
    );
  }
}

/// Widget for category selection option.
class _CategoryOption extends StatelessWidget {
  final String title;
  final bool isSelected;
  final VoidCallback onTap;

  const _CategoryOption({
    required this.title,
    required this.isSelected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          border: Border.all(
            color: isSelected
                ? theme.colorScheme.primary
                : theme.colorScheme.outline.withOpacity(0.3),
            width: isSelected ? 2 : 1,
          ),
          borderRadius: BorderRadius.circular(12),
          color: isSelected
              ? theme.colorScheme.primary.withOpacity(0.1)
              : null,
        ),
        child: Row(
          children: [
            Icon(
              isSelected ? Icons.check_circle : Icons.circle_outlined,
              color: isSelected
                  ? theme.colorScheme.primary
                  : theme.colorScheme.onSurface.withOpacity(0.4),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                title,
                style: theme.textTheme.bodyMedium?.copyWith(
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                  color: isSelected
                      ? theme.colorScheme.primary
                      : theme.colorScheme.onSurface,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
