import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../models/circle_model.dart';
import '../../providers/circles_provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/user_provider.dart';
import '../../widgets/forms/styled_text_field.dart';
import '../../widgets/forms/tag_selector.dart';
import '../../widgets/buttons/primary_button.dart';
import '../../widgets/common/loading_indicator.dart';
import '../../config/constants.dart';

/// Screen for creating a new circle.
class AddCircleScreen extends StatefulWidget {
  const AddCircleScreen({super.key});

  @override
  State<AddCircleScreen> createState() => _AddCircleScreenState();
}

class _AddCircleScreenState extends State<AddCircleScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _meetingLinkController = TextEditingController();
  final _addressController = TextEditingController();
  final _onlineCapacityController = TextEditingController();
  final _inPersonCapacityController = TextEditingController();

  CircleFormat _selectedFormat = CircleFormat.online;
  DateTime _selectedDate = DateTime.now().add(const Duration(days: 1));
  TimeOfDay _selectedTime = const TimeOfDay(hour: 18, minute: 0);
  List<String> _selectedTags = [];
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _meetingLinkController.dispose();
    _addressController.dispose();
    _onlineCapacityController.dispose();
    _inPersonCapacityController.dispose();
    super.dispose();
  }

  void _onFormatChanged(CircleFormat format) {
    setState(() {
      _selectedFormat = format;
    });
  }

  void _onTagsChanged(List<String> tags) {
    setState(() {
      _selectedTags = tags;
    });
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  Future<void> _selectTime() async {
    final picked = await showTimePicker(
      context: context,
      initialTime: _selectedTime,
    );
    if (picked != null) {
      setState(() {
        _selectedTime = picked;
      });
    }
  }

  DateTime get _scheduledDateTime {
    return DateTime(
      _selectedDate.year,
      _selectedDate.month,
      _selectedDate.day,
      _selectedTime.hour,
      _selectedTime.minute,
    );
  }

  Future<void> _createCircle() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Validate format-specific fields
    if (_selectedFormat != CircleFormat.inPerson &&
        _meetingLinkController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please provide a meeting link for online attendance'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    if (_selectedFormat != CircleFormat.online &&
        _addressController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please provide an address for in-person attendance'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final authProvider = context.read<AuthProvider>();
      final userProvider = context.read<UserProvider>();
      final circlesProvider = context.read<CirclesProvider>();

      final userId = authProvider.userId;
      final user = userProvider.currentUser;

      if (userId == null || user == null) {
        throw Exception('You must be logged in to create a circle');
      }

      final circle = CircleModel(
        id: '', // Will be generated by Firestore
        creatorUid: userId,
        creatorName: user.displayName,
        creatorPhotoUrl: user.photoUrl,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        format: _selectedFormat,
        meetingLink: _selectedFormat != CircleFormat.inPerson
            ? _meetingLinkController.text.trim()
            : null,
        address: _selectedFormat != CircleFormat.online
            ? _addressController.text.trim()
            : null,
        onlineCapacity: _selectedFormat != CircleFormat.inPerson &&
                _onlineCapacityController.text.isNotEmpty
            ? int.tryParse(_onlineCapacityController.text)
            : null,
        inPersonCapacity: _selectedFormat != CircleFormat.online &&
                _inPersonCapacityController.text.isNotEmpty
            ? int.tryParse(_inPersonCapacityController.text)
            : null,
        scheduledDate: _scheduledDateTime,
        tags: _selectedTags,
        attendeeIds: [],
        createdAt: DateTime.now(),
      );

      final circleId = await circlesProvider.createCircle(circle);

      if (circleId != null && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Circle created successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        context.pop();
      } else if (mounted) {
        throw Exception(circlesProvider.error ?? 'Failed to create circle');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Circle'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.pop(),
        ),
      ),
      body: _isLoading
          ? const LoadingIndicator(message: 'Creating circle...')
          : Form(
              key: _formKey,
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  // Title Input
                  Text(
                    'Title',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  StyledTextField(
                    controller: _titleController,
                    hintText: 'Give your circle a name...',
                    textCapitalization: TextCapitalization.words,
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter a title';
                      }
                      if (value.trim().length < 5) {
                        return 'Title must be at least 5 characters';
                      }
                      return null;
                    },
                  ),

                  const SizedBox(height: 24),

                  // Description Input
                  Text(
                    'Description',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  StyledTextField(
                    controller: _descriptionController,
                    hintText: 'What will you discuss in this circle?',
                    maxLines: 4,
                    textCapitalization: TextCapitalization.sentences,
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter a description';
                      }
                      if (value.trim().length < 20) {
                        return 'Description must be at least 20 characters';
                      }
                      return null;
                    },
                  ),

                  const SizedBox(height: 24),

                  // Format Selection
                  Text(
                    'Format',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: CircleFormat.values.map((format) {
                      return Expanded(
                        child: Padding(
                          padding: EdgeInsets.only(
                            right: format != CircleFormat.values.last ? 8 : 0,
                          ),
                          child: _FormatOption(
                            format: format,
                            isSelected: _selectedFormat == format,
                            onTap: () => _onFormatChanged(format),
                          ),
                        ),
                      );
                    }).toList(),
                  ),

                  const SizedBox(height: 24),

                  // Meeting Link (for Online or Both)
                  if (_selectedFormat != CircleFormat.inPerson) ...[
                    Text(
                      'Meeting Link',
                      style: theme.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),
                    StyledTextField(
                      controller: _meetingLinkController,
                      hintText: 'https://zoom.us/j/...',
                      keyboardType: TextInputType.url,
                      prefixIcon: const Icon(Icons.link),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Online Capacity (Optional)',
                      style: theme.textTheme.titleSmall,
                    ),
                    const SizedBox(height: 8),
                    StyledTextField(
                      controller: _onlineCapacityController,
                      hintText: 'Leave empty for unlimited',
                      keyboardType: TextInputType.number,
                      prefixIcon: const Icon(Icons.people_outline),
                      inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                    ),
                    const SizedBox(height: 24),
                  ],

                  // Address (for In-Person or Both)
                  if (_selectedFormat != CircleFormat.online) ...[
                    Text(
                      'Address',
                      style: theme.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),
                    StyledTextField(
                      controller: _addressController,
                      hintText: 'Where will you meet?',
                      maxLines: 2,
                      textCapitalization: TextCapitalization.sentences,
                      prefixIcon: const Icon(Icons.location_on_outlined),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'In-Person Capacity (Optional)',
                      style: theme.textTheme.titleSmall,
                    ),
                    const SizedBox(height: 8),
                    StyledTextField(
                      controller: _inPersonCapacityController,
                      hintText: 'Leave empty for unlimited',
                      keyboardType: TextInputType.number,
                      prefixIcon: const Icon(Icons.people_outline),
                      inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                    ),
                    const SizedBox(height: 24),
                  ],

                  // Date and Time Selection
                  Text(
                    'Date & Time',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Expanded(
                        child: _DateTimeSelector(
                          icon: Icons.calendar_today,
                          label: DateFormat.yMMMd().format(_selectedDate),
                          onTap: _selectDate,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _DateTimeSelector(
                          icon: Icons.access_time,
                          label: _selectedTime.format(context),
                          onTap: _selectTime,
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: 24),

                  // Tag Selection
                  Text(
                    'Tags (Optional)',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Select up to ${AppConstants.maxTagsPerItem} tags to help others find your circle',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurface.withOpacity(0.6),
                    ),
                  ),
                  const SizedBox(height: 12),

                  // Personal Growth tags
                  Text(
                    'Personal Growth',
                    style: theme.textTheme.titleSmall?.copyWith(
                      color: theme.colorScheme.primary,
                    ),
                  ),
                  const SizedBox(height: 8),
                  TagSelector.personalGrowth(
                    selectedTags: _selectedTags,
                    onChanged: _onTagsChanged,
                    maxSelections: AppConstants.maxTagsPerItem,
                  ),

                  const SizedBox(height: 16),

                  // Social & Political tags
                  Text(
                    'Social & Political',
                    style: theme.textTheme.titleSmall?.copyWith(
                      color: theme.colorScheme.secondary,
                    ),
                  ),
                  const SizedBox(height: 8),
                  TagSelector.socialPolitical(
                    selectedTags: _selectedTags,
                    onChanged: _onTagsChanged,
                    maxSelections: AppConstants.maxTagsPerItem,
                  ),

                  const SizedBox(height: 32),

                  // Create Button
                  PrimaryButton(
                    text: 'Create Circle',
                    onPressed: _createCircle,
                    icon: Icons.group_add,
                  ),

                  const SizedBox(height: 24),
                ],
              ),
            ),
    );
  }
}

/// Widget for format selection option.
class _FormatOption extends StatelessWidget {
  final CircleFormat format;
  final bool isSelected;
  final VoidCallback onTap;

  const _FormatOption({
    required this.format,
    required this.isSelected,
    required this.onTap,
  });

  IconData get _icon {
    switch (format) {
      case CircleFormat.online:
        return Icons.videocam_outlined;
      case CircleFormat.inPerson:
        return Icons.place_outlined;
      case CircleFormat.both:
        return Icons.public;
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),
        decoration: BoxDecoration(
          border: Border.all(
            color: isSelected
                ? theme.colorScheme.primary
                : theme.colorScheme.outline.withOpacity(0.3),
            width: isSelected ? 2 : 1,
          ),
          borderRadius: BorderRadius.circular(12),
          color:
              isSelected ? theme.colorScheme.primary.withOpacity(0.1) : null,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              _icon,
              color: isSelected
                  ? theme.colorScheme.primary
                  : theme.colorScheme.onSurface.withOpacity(0.6),
            ),
            const SizedBox(height: 4),
            Text(
              format.label,
              style: theme.textTheme.bodySmall?.copyWith(
                fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                color: isSelected
                    ? theme.colorScheme.primary
                    : theme.colorScheme.onSurface,
              ),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}

/// Widget for date/time selection.
class _DateTimeSelector extends StatelessWidget {
  final IconData icon;
  final String label;
  final VoidCallback onTap;

  const _DateTimeSelector({
    required this.icon,
    required this.label,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          border: Border.all(
            color: theme.colorScheme.outline.withOpacity(0.3),
          ),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Row(
          children: [
            Icon(
              icon,
              color: theme.colorScheme.primary,
              size: 20,
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                label,
                style: theme.textTheme.bodyMedium,
              ),
            ),
            Icon(
              Icons.arrow_drop_down,
              color: theme.colorScheme.onSurface.withOpacity(0.5),
            ),
          ],
        ),
      ),
    );
  }
}
